using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NebulaNewsSystem.Web.Data.Migrations
{
    public partial class AutoGeneratedIdsAndSeedDB : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Title",
                table: "Articles",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(40)",
                oldMaxLength: 40);

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Politics" },
                    { 2, "Business and Economy" },
                    { 3, "Health and Wellness" },
                    { 4, "Entertainment and celebrities" },
                    { 5, "Sports" },
                    { 6, "Science and Environment" },
                    { 7, "Crime" },
                    { 8, "Technology" },
                    { 9, "Culture and Lifestyle" },
                    { 10, "Education" },
                    { 11, "Opinion and Editorial" }
                });

            migrationBuilder.InsertData(
                table: "Articles",
                columns: new[] { "ArticleId", "AuthorId", "CategoryId", "Content", "ImageUrl", "PublicationDate", "Title" },
                values: new object[] { new Guid("3c74cdaa-71b0-4789-89e0-93c72fd2e8a9"), new Guid("439455a8-590b-4fd3-a3f6-5cf16729dbb2"), 1, "The transformation of the mineral water borehole in the village of Bistrica into an object of primary importance for the municipality will be the subject of debate at an extraordinary session in Dupnitsa. The report was entered by the councilor from \"Voice of the People\" Gichka Mihailova. We recall that she would alarm that the firm involved in the study was considering a withdrawal.", "https://4vlast-bg.com/wp-content/uploads/2023/12/403389284_682223740702741_5157933701577735441_n.jpg", new DateTime(2024, 3, 12, 23, 0, 0, 0, DateTimeKind.Unspecified), "The municipal council of Dupnitsa meets because of the mineral water in Bistritsa" });

            migrationBuilder.InsertData(
                table: "Articles",
                columns: new[] { "ArticleId", "AuthorId", "CategoryId", "Content", "ImageUrl", "PublicationDate", "Title" },
                values: new object[] { new Guid("49cde94c-3f90-4f95-8e91-a751aa2b7af4"), new Guid("439455a8-590b-4fd3-a3f6-5cf16729dbb2"), 10, "The results of the competitions for principals of three Dupnitsa's schools are known now. Lyubomir Georgiev was elected as the director of \"Hristo Botev\" Profesional Gymnasium. He is a physical education teacher, baseball coach and former city councilman. The incumbent Gergana Milenkova dropped out of the race for the post. In head of secondary language school \"St. Paisiy Hilendarski\" remains Anelia Yordanova. She took over the leadership of the largest drilling school two years ago until a competition was held. Director of General Educational School \"St. Kliment Ohridski\" remains Juliana Borisova, who was the only candidate.", "https://static.bnr.bg/gallery/cr/3ae7c802129b9a9ae5af2da27e6a183a.jpg", new DateTime(2024, 3, 12, 22, 30, 0, 0, DateTimeKind.Unspecified), "The results of the competitions for principals of schools in Dupnitsa are known" });

            migrationBuilder.InsertData(
                table: "Articles",
                columns: new[] { "ArticleId", "AuthorId", "CategoryId", "Content", "ImageUrl", "PublicationDate", "Title" },
                values: new object[] { new Guid("550f78bf-9c45-4fa1-9a1e-4af3a5192be6"), new Guid("439455a8-590b-4fd3-a3f6-5cf16729dbb2"), 7, "A 17-year-old unlicensed driver of a Mercedes was detained last night by Dupnitsa's policemen. They carried out the inspection in the area of Sapareva Banya, and also found that the inspected car had registration plates issued for another vehicle. A quick police investigation was initiated in the Dupnitsa Intelligence Department, the prosecutor's office was notified.", "https://i.id24.bg/i/1616547.jpg", new DateTime(2024, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified), "A 17-year-old who drove a Mercedes both without a license and with fake license plates arrested" });

            migrationBuilder.InsertData(
                table: "Comment",
                columns: new[] { "CommentId", "ArticleId", "CommenterId", "Content", "CreationDate" },
                values: new object[] { new Guid("1ce4973f-a458-4777-ac31-9032bd11f426"), new Guid("550f78bf-9c45-4fa1-9a1e-4af3a5192be6"), "20cd7080-3221-4b5e-96c9-f6ebd93555de", "emi za tova se praviat tolkova katastrofi, triabva da se vzemat merki", new DateTime(2024, 3, 14, 16, 31, 41, 756, DateTimeKind.Local).AddTicks(3507) });

            migrationBuilder.InsertData(
                table: "Comment",
                columns: new[] { "CommentId", "ArticleId", "CommenterId", "Content", "CreationDate" },
                values: new object[] { new Guid("53e508ee-3a15-4d7a-868a-00c38be79b84"), new Guid("49cde94c-3f90-4f95-8e91-a751aa2b7af4"), "247929cd-14da-4c78-bcc7-92fb93e300a1", "Dobre e taka, triabva da se vkara malko disciplina v gimnazijata", new DateTime(2024, 3, 14, 16, 31, 41, 756, DateTimeKind.Local).AddTicks(3457) });

            migrationBuilder.InsertData(
                table: "Comment",
                columns: new[] { "CommentId", "ArticleId", "CommenterId", "Content", "CreationDate" },
                values: new object[] { new Guid("a57e0fc2-96d6-41e8-ac14-aaf5f91872b4"), new Guid("3c74cdaa-71b0-4789-89e0-93c72fd2e8a9"), "5c65b87d-ab20-4314-bf26-4c7dbcca0924", "Bravo na Gi4ka, da gi razkara oti stanali sa mnogo nagli", new DateTime(2024, 3, 14, 16, 31, 41, 756, DateTimeKind.Local).AddTicks(3513) });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 5);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 6);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 8);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 9);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 11);

            migrationBuilder.DeleteData(
                table: "Comment",
                keyColumn: "CommentId",
                keyValue: new Guid("1ce4973f-a458-4777-ac31-9032bd11f426"));

            migrationBuilder.DeleteData(
                table: "Comment",
                keyColumn: "CommentId",
                keyValue: new Guid("53e508ee-3a15-4d7a-868a-00c38be79b84"));

            migrationBuilder.DeleteData(
                table: "Comment",
                keyColumn: "CommentId",
                keyValue: new Guid("a57e0fc2-96d6-41e8-ac14-aaf5f91872b4"));

            migrationBuilder.DeleteData(
                table: "Articles",
                keyColumn: "ArticleId",
                keyValue: new Guid("3c74cdaa-71b0-4789-89e0-93c72fd2e8a9"));

            migrationBuilder.DeleteData(
                table: "Articles",
                keyColumn: "ArticleId",
                keyValue: new Guid("49cde94c-3f90-4f95-8e91-a751aa2b7af4"));

            migrationBuilder.DeleteData(
                table: "Articles",
                keyColumn: "ArticleId",
                keyValue: new Guid("550f78bf-9c45-4fa1-9a1e-4af3a5192be6"));

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 7);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 10);

            migrationBuilder.AlterColumn<string>(
                name: "Title",
                table: "Articles",
                type: "nvarchar(40)",
                maxLength: 40,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(100)",
                oldMaxLength: 100);
        }
    }
}
